name: Flutter Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug Directory Structure
      run: |
        echo "=== Current Working Directory ==="
        pwd
        echo "=== Search for pubspec.yaml ==="
        find . -name "pubspec.yaml"
        echo "=== Directory List ==="
        ls -la

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'

    - name: Install dependencies & Build APK
      run: |
        TARGET_DIR=$(dirname $(find . -name "pubspec.yaml" | head -n 1))
        echo "Moving to Flutter root: $TARGET_DIR"
        cd "$TARGET_DIR"
        flutter pub get
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: zadam-app-release
        path: "**/app-release.apk"
